[project]
name = "FICSIT-Fred"
version = "2.18.2"
description = "A Discord bot for the Satisfactory Modding Discord "
readme = "README.md"
requires-python = "~=3.10"
license = {file="LICENSE"}
authors = [
    { name = "Feyko", email = "feykook@gmail.com"}, 
    { name = "Mircea Roata", email = "mircearoatapalade@yahoo.ro"},
    { name = "Astro Floof", email = "does.not.kompute@gmail.com"}
]
dependencies = [
    "nextcord ~= 2.0.0a8",
    "Pillow ~= 9.0",
    "pytesseract ~= 0.3.8",
    "psycopg2-binary ~= 2.9",
    "python-dotenv ~= 0.19",
    "jsonpickle ~= 2.1",
    "algoliasearch ~= 2.6",
    "SQLObject ~= 3.9",
    "google-cloud-dialogflow ~= 2.11"
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
