[tool.poetry]
name = "ficsit-fred"
version = "2.18.0"
description = ""
authors = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
nextcord = "^2.0.0-alpha.6"
Pillow = "^9.0.0"
pytesseract = "^0.3.8"
psycopg2-binary = "^2.9.3"
python-dotenv = "^0.19.2"
jsonpickle = "^2.1.0"
algoliasearch = "^2.6.1"
SQLObject = "^3.9.1"
google-cloud-dialogflow = "^2.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
